### ISSUE TITLE
New improved version.

### ISSUE THREAD

**Issue by phadej** [jonpetterbergman/step-function#1]
Hi Petter,

I found that I need step functions in my own developments, and made an implementation, to only later realize that you have made a variant already. I think my version is however "better", and it would be great if we could merge our efforts.

What you think, can my variant become `step-function-0.2`. Obviously I'll help to maintain and develop package in the future.

The source code is at: https://github.com/phadej/step-function
And the haddocks: http://oleg.fi/step-function/

A comment about dependencies, on GHC-8.2.2 the non-bundled dependencies are:
```
base-compat-batteries-0.10.1
base-compat-0.10.1

QuickCheck-2.11.3
tf-random-0.5
primitive-0.6.3.0
random-1.1
```

First group helps to push support to very old GHC with little efforts, the latter is dependency on `QuickCheck`. I think it's lightweight enough - and `Arbitrary` step function was at least useful to test the implementation itself.

Cheers, Oleg

**Comment by jonpetterbergman** [comment]
Hi Oleg,

I haven't done any development on step-function in some time, just bumping
dependencies once i a while.

Would you like to become the maintainer? I agree that your version is
better.

I factored out step-function from an online booking system I did somewhere
around 2014/15, where resource utilization was represented using step
function. Feels like a long time ago.

MVH

Petter Bergman

2018-05-19 16:24 GMT+02:00 Oleg Grenrus <notifications@github.com>:

**Comment by phadej** [comment]
@jonpetterbergman becoming a (co-)maintainer suits me well! Thanks in advance!

**Comment by jonpetterbergman** [comment]
I have added you as collaborator on GitHub. What is your username on
Hackage?

/Petter

2018-05-19 22:55 GMT+02:00 Oleg Grenrus <notifications@github.com>:

**Comment by phadej** [comment]
It's also `phadej`. http://hackage.haskell.org/user/phadej

While you are on it, do you mind enabling https://travis-ci.org/ for this repository, I'd like to setup CI, but one needs to be an owner to turn that on. Thanks in advance, again.

**Comment by jonpetterbergman** [comment]
Right, under "Integrations & services"?

2018-05-20 20:15 GMT+02:00 Oleg Grenrus <notifications@github.com>:

**Comment by jonpetterbergman** [comment]
Travis CI should now be enabled, I've also added you as maintainer on
Hackage.

2018-05-20 20:17 GMT+02:00 Petter Bergman <jon.petter.bergman@gmail.com>:
